export interface BranchSkillOption {
  category: string;
  skills: string[];
}

export const BRANCH_SKILLS_MAP: Record<string, string[]> = {
  "Computer Engineering": [
    "Basic Programming",
    "C",
    "C++",
    "Java",
    "Python",
    "JavaScript",
    "Data Structures",
    "Algorithms",
    "OOP",
    "DBMS",
    "Operating Systems",
    "Computer Networks",
    "Web Development",
    "SQL",
    "Git",
    "HTML & CSS",
  ],
  "Information Technology": [
    "Basic Programming",
    "C++",
    "Java",
    "Python",
    "Web Development",
    "Data Structures",
    "Algorithms",
    "Cloud Computing",
    "Cyber Security",
    "DBMS",
    "Computer Networks",
    "SQL",
    "Git",
  ],
  "Artificial Intelligence & Data Science": [
    "Python",
    "R",
    "Data Structures",
    "Algorithms",
    "Linear Algebra & Stats",
    "Machine Learning Basics",
    "Pandas & NumPy",
    "SQL",
    "Data Visualization",
    "Deep Learning",
    "Git",
  ],
  "Artificial Intelligence & Machine Learning": [
    "Python",
    "C++",
    "Data Structures",
    "Linear Algebra",
    "Machine Learning Algorithms",
    "Deep Learning",
    "TensorFlow / PyTorch",
    "Computer Vision",
    "NLP",
    "Git",
  ],
  "Mechanical Engineering": [
    "Engineering Mechanics",
    "AutoCAD",
    "SolidWorks",
    "Thermodynamics",
    "Fluid Mechanics",
    "Manufacturing Processes",
    "Heat Transfer",
    "Machine Design",
    "Material Science",
    "MATLAB",
  ],
  "Civil Engineering": [
    "Structural Analysis",
    "AutoCAD Civil",
    "Surveying",
    "Concrete Technology",
    "Geotechnical Engineering",
    "Fluid Mechanics",
    "Transportation Engineering",
    "Construction Management",
    "STAAD Pro",
  ],
  "Electronics & Telecommunication": [
    "Digital Electronics",
    "Analog Circuits",
    "Microcontrollers (8051/ARM)",
    "Signals & Systems",
    "Embedded C",
    "Communication Systems",
    "MATLAB",
    "Verilog / VHDL",
    "Arduino & IoT",
  ],
  "Electronics Engineering": [
    "Basic Electrical",
    "Analog Circuits",
    "Digital Logic Design",
    "Microprocessors",
    "Circuit Simulation (SPICE)",
    "PCB Design",
    "VLSI Basics",
    "Embedded Systems",
  ],
  "Electrical Engineering": [
    "Circuit Theory",
    "Electrical Machines",
    "Power Systems",
    "Control Systems",
    "Power Electronics",
    "MATLAB / Simulink",
    "Renewable Energy Basics",
    "Electrical Measurements",
  ],
  "Other": [
    "Basic Programming",
    "Python",
    "C++",
    "Microsoft Excel & Analytics",
    "Problem Solving",
    "Mathematics & Statistics",
    "Git & GitHub",
  ],
};

export function getSkillsForBranch(branch?: string | null): string[] {
  if (!branch) return BRANCH_SKILLS_MAP["Computer Engineering"];
  return BRANCH_SKILLS_MAP[branch] || BRANCH_SKILLS_MAP["Other"];
}
