import { jsPDF } from "jspdf";

export interface TopicPdfOptions {
  title: string;
  courseName?: string;
  moduleName?: string;
  content?: string;
  category?: string;
  author?: string;
  estimatedTime?: string;
}

export interface ModuleNotesData {
  title: string;
  topics: {
    title: string;
    notesContent?: string | null;
    estimatedTime?: string;
  }[];
}

export function downloadTopicNotesPdf(options: TopicPdfOptions): void {
  const {
    title,
    courseName = "LearnFlow Engineering Curriculum",
    moduleName = "Core Engineering Module",
    content = "",
    category = "Engineering",
    estimatedTime = "15-20 mins",
  } = options;

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  const maxY = pageHeight - 20;

  function drawHeaderAndFooter(pageNum: number) {
    // Top banner (Engineering Blue)
    doc.setFillColor(30, 58, 138); // #1e3a8a
    doc.rect(0, 0, pageWidth, 22, "F");

    // Golden/Sky accent line
    doc.setFillColor(59, 130, 246); // #3b82f6
    doc.rect(0, 20, pageWidth, 2, "F");

    // Header text
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("LEARNFLOW ENGINEERING STUDY NOTES", margin, 10);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.text("VERIFIED CURRICULUM • EXAM & INTERVIEW REVISION GUIDE", margin, 15);

    if (courseName) {
      doc.setFontSize(8);
      const safeCourse = courseName.length > 35 ? courseName.slice(0, 35) + "..." : courseName;
      doc.text(safeCourse.toUpperCase(), pageWidth - margin, 11, { align: "right" });
    }

    // Top Right Category Pill
    if (category) {
      doc.setFontSize(7);
      doc.text(`[ ${category} ]`, pageWidth - margin, 16, { align: "right" });
    }

    // Footer divider line
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

    // Footer text
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by LearnFlow AI Study Assistant • Academic & Interview Preparation", margin, pageHeight - 7);
  }

  let y = 32;
  drawHeaderAndFooter(1);

  // Document Title
  doc.setTextColor(15, 23, 42); // slate-900
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  const titleLines = doc.splitTextToSize(title, contentWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 7 + 2;

  // Metadata Card / Bar
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(margin, y, contentWidth, 10, 2, 2, "FD");

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  const todayStr = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
  const metaLine = `Module: ${moduleName}   |   Est. Read: ${estimatedTime}   |   Revision Date: ${todayStr}`;
  doc.text(metaLine, margin + 4, y + 6.5);
  y += 16;

  // Process Markdown Content
  const fallbackText = content || `# ${title}\n\nNotes for this topic are currently being expanded with AI-driven comprehensive definitions and derivations.\n\n- Core concepts and algorithms\n- High-yield interview patterns\n- Implementation templates`;
  const lines = fallbackText.split("\n");

  let inCodeBlock = false;
  let codeBuffer: string[] = [];

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];

    // Check page overflow
    if (y > maxY) {
      doc.addPage();
      drawHeaderAndFooter(doc.getNumberOfPages());
      y = 30;
    }

    // Code block detection
    if (rawLine.trim().startsWith("```")) {
      if (inCodeBlock) {
        // Flush code block
        inCodeBlock = false;
        doc.setFillColor(241, 245, 249); // slate-100
        doc.setDrawColor(203, 213, 225); // slate-300
        doc.setFont("courier", "normal");
        doc.setFontSize(7.5);
        doc.setTextColor(30, 41, 59);

        const codeLineHeight = 4.2;
        const codeBoxHeight = codeBuffer.length * codeLineHeight + 6;

        if (y + codeBoxHeight > maxY) {
          doc.addPage();
          drawHeaderAndFooter(doc.getNumberOfPages());
          y = 30;
        }

        doc.roundedRect(margin, y, contentWidth, codeBoxHeight, 2, 2, "FD");

        let codeY = y + 5;
        codeBuffer.forEach((cl) => {
          const safeCl = cl.replace(/\t/g, "  ");
          doc.text(safeCl, margin + 4, codeY);
          codeY += codeLineHeight;
        });

        y += codeBoxHeight + 5;
        codeBuffer = [];
      } else {
        inCodeBlock = true;
        codeBuffer = [];
      }
      continue;
    }

    if (inCodeBlock) {
      codeBuffer.push(rawLine);
      continue;
    }

    const trimmed = rawLine.trim();
    if (!trimmed) {
      y += 2.5;
      continue;
    }

    // H1 Heading
    if (trimmed.startsWith("# ")) {
      y += 4;
      if (y > maxY) {
        doc.addPage();
        drawHeaderAndFooter(doc.getNumberOfPages());
        y = 30;
      }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(30, 58, 138); // blue-900
      const heading = trimmed.replace("# ", "").replace(/\*\*/g, "");
      doc.text(heading, margin, y);
      y += 5;
      doc.setDrawColor(191, 219, 254);
      doc.setLineWidth(0.4);
      doc.line(margin, y, margin + 50, y);
      y += 4;
    }
    // H2 Heading
    else if (trimmed.startsWith("## ")) {
      y += 3;
      if (y > maxY) {
        doc.addPage();
        drawHeaderAndFooter(doc.getNumberOfPages());
        y = 30;
      }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(30, 64, 175); // blue-800
      const heading = trimmed.replace("## ", "").replace(/\*\*/g, "");
      doc.text(heading, margin, y);
      y += 5.5;
    }
    // H3 Heading
    else if (trimmed.startsWith("### ")) {
      y += 2;
      if (y > maxY) {
        doc.addPage();
        drawHeaderAndFooter(doc.getNumberOfPages());
        y = 30;
      }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(51, 65, 85); // slate-700
      const heading = trimmed.replace("### ", "").replace(/\*\*/g, "");
      doc.text(heading, margin, y);
      y += 4.5;
    }
    // Blockquote
    else if (trimmed.startsWith("> ")) {
      if (y > maxY - 10) {
        doc.addPage();
        drawHeaderAndFooter(doc.getNumberOfPages());
        y = 30;
      }
      const quote = trimmed.replace("> ", "").replace(/\*\*/g, "");
      const wrappedQuote = doc.splitTextToSize(quote, contentWidth - 12);
      const quoteHeight = wrappedQuote.length * 4.2 + 4;

      doc.setFillColor(239, 246, 255); // blue-50
      doc.setDrawColor(147, 197, 253); // blue-300
      doc.roundedRect(margin, y, contentWidth, quoteHeight, 1.5, 1.5, "FD");

      doc.setFillColor(37, 99, 235); // blue-600
      doc.rect(margin, y, 2.5, quoteHeight, "F");

      doc.setFont("helvetica", "italic");
      doc.setFontSize(8.5);
      doc.setTextColor(30, 58, 138);
      doc.text(wrappedQuote, margin + 6, y + 4.5);

      y += quoteHeight + 4;
    }
    // Bullet item
    else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(30, 41, 59);

      const bulletText = trimmed.replace(/^[-*]\s+/, "").replace(/\*\*/g, "");
      const wrapped = doc.splitTextToSize(bulletText, contentWidth - 8);

      if (y + wrapped.length * 4.2 > maxY) {
        doc.addPage();
        drawHeaderAndFooter(doc.getNumberOfPages());
        y = 30;
      }

      doc.setFillColor(59, 130, 246);
      doc.circle(margin + 2, y - 0.8, 0.7, "F");
      doc.text(wrapped, margin + 6, y);
      y += wrapped.length * 4.2 + 1.2;
    }
    // Numbered list item
    else if (/^\d+\.\s/.test(trimmed)) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(30, 41, 59);

      const match = trimmed.match(/^(\d+)\.\s+(.*)/);
      const num = match ? match[1] + "." : "•";
      const rest = (match ? match[2] : trimmed).replace(/\*\*/g, "");
      const wrapped = doc.splitTextToSize(rest, contentWidth - 10);

      if (y + wrapped.length * 4.2 > maxY) {
        doc.addPage();
        drawHeaderAndFooter(doc.getNumberOfPages());
        y = 30;
      }

      doc.setFont("helvetica", "bold");
      doc.setTextColor(37, 99, 235);
      doc.text(num, margin + 1, y);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(30, 41, 59);
      doc.text(wrapped, margin + 8, y);
      y += wrapped.length * 4.2 + 1.5;
    }
    // Regular paragraph text
    else {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(51, 65, 85);

      const cleanLine = trimmed.replace(/\*\*/g, "");
      const wrapped = doc.splitTextToSize(cleanLine, contentWidth);

      if (y + wrapped.length * 4.2 > maxY) {
        doc.addPage();
        drawHeaderAndFooter(doc.getNumberOfPages());
        y = 30;
      }

      doc.text(wrapped, margin, y);
      y += wrapped.length * 4.2 + 1.8;
    }
  }

  // Update Page numbers in footer
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${p} of ${totalPages}`, pageWidth - margin, pageHeight - 7, { align: "right" });
  }

  // Sanitize filename
  const cleanTitle = title
    .replace(/[^a-zA-Z0-9_-]/g, "_")
    .replace(/_+/g, "_")
    .slice(0, 40);

  doc.save(`Learnflow_${cleanTitle}_Notes.pdf`);
}

export function downloadCourseMasterPdf(
  courseTitle: string,
  modules: { title: string; topics: { title: string; notesContent?: string | null }[] }[]
): void {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  const maxY = pageHeight - 20;

  function drawHeader(pageNum: number) {
    doc.setFillColor(30, 58, 138);
    doc.rect(0, 0, pageWidth, 22, "F");
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 20, pageWidth, 2, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("LEARNFLOW MASTER COURSE COMPENDIUM", margin, 10);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.text(courseTitle.toUpperCase(), margin, 16);

    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text("LearnFlow Engineering Curriculum • Complete Course Notes", margin, pageHeight - 7);
  }

  let y = 34;
  drawHeader(1);

  // Cover / Header
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  const titleLines = doc.splitTextToSize(courseTitle, contentWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 8 + 4;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text(`Complete Engineering Notes Compendium • ${modules.length} Modules Included`, margin, y);
  y += 10;

  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  for (let m = 0; m < modules.length; m++) {
    const mod = modules[m];

    if (y > maxY - 20) {
      doc.addPage();
      drawHeader(doc.getNumberOfPages());
      y = 30;
    }

    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, y, contentWidth, 9, 1.5, 1.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(30, 58, 138);
    doc.text(`Module ${m + 1}: ${mod.title}`, margin + 4, y + 6);
    y += 14;

    for (const topic of mod.topics) {
      if (y > maxY - 15) {
        doc.addPage();
        drawHeader(doc.getNumberOfPages());
        y = 30;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      doc.text(`• ${topic.title}`, margin + 2, y);
      y += 5.5;

      const bodyText = (topic.notesContent || "Comprehensive notes included in single topic study sheet.")
        .replace(/#+\s+/g, "")
        .replace(/\*\*/g, "")
        .split("\n")
        .filter((l) => l.trim().length > 0)
        .slice(0, 4)
        .join(" ");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);
      const wrapped = doc.splitTextToSize(bodyText, contentWidth - 6);
      doc.text(wrapped, margin + 6, y);
      y += wrapped.length * 3.8 + 5;
    }
  }

  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${p} of ${totalPages}`, pageWidth - margin, pageHeight - 7, { align: "right" });
  }

  const cleanCourse = courseTitle
    .replace(/[^a-zA-Z0-9_-]/g, "_")
    .replace(/_+/g, "_")
    .slice(0, 35);

  doc.save(`Learnflow_${cleanCourse}_Master_Notes.pdf`);
}
